package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.Date;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;

public class HoaDon_GUI extends JPanel{
	private JTextField txtMaHD;
	private JTextField txtNgayLapHD;
	private JTextField txtNV;
	private JTextField txtTenKH;
	private JTextField txtDiaChi;
	private JTextField txtSDT;
	private DefaultTableModel model;
	private JTable table;
	private JTextField txtTenThuoc;
	private JTextField txtSoLuong;
	private JTextField txtDonGia;
	private JButton btnThem;
	private JButton btnXoa;
	private JButton btnQuayLai;
	private JTextField txtTongTien;

	public HoaDon_GUI() {
//		setTitle("Hóa đơn");
//		setSize(700, 500);
//		setLocationRelativeTo(null);
//		setDefaultCloseOperation(EXIT_ON_CLOSE);
//		setResizable(false);
		
		this.setLayout(new BorderLayout());
		this.setPreferredSize(new Dimension(700, 500));
		JPanel pMain = new JPanel();
		pMain.setLayout(new BorderLayout());
		this.add(pMain,BorderLayout.NORTH);
		JPanel pNorth = new JPanel();
		pNorth.setLayout(new GridLayout(3, 2));
		
		JLabel lblMaHD = new JLabel("Mã hóa đơn: ");
		txtMaHD = new JTextField(15);
		JLabel lblNgayLapHD = new JLabel("Ngày lập hóa đơn: ");
		txtNgayLapHD = new JTextField(15);
		JLabel lblNV = new JLabel("Tên nhân viên: ");
		txtNV = new JTextField(15);
		JLabel lblTenKH = new JLabel("Tên khách hàng: ");
		txtTenKH = new JTextField(15);
		JLabel lblDiaChi = new JLabel("Địa chỉ: ");
		txtDiaChi = new JTextField(15);
		JLabel lblSDT = new JLabel("Số điện thoại: ");
		txtSDT = new JTextField(15);
		pNorth.add(lblMaHD);
		pNorth.add(txtMaHD);
		pNorth.add(lblTenKH);
		pNorth.add(txtTenKH);
		pNorth.add(lblNgayLapHD);
		pNorth.add(txtNgayLapHD);
		pNorth.add(lblDiaChi);
		pNorth.add(txtDiaChi);
		pNorth.add(lblNV);
		pNorth.add(txtNV);
		pNorth.add(lblSDT);
		pNorth.add(txtSDT);
		pMain.add(pNorth,BorderLayout.NORTH);
		Border borderNorth = BorderFactory.createLineBorder(Color.BLUE);
		TitledBorder titleBorderNorth = new TitledBorder(borderNorth, "Nhập thông tin");
		pNorth.setBorder(titleBorderNorth);
		pNorth.setBackground(Color.pink);
		JPanel pCenter = new JPanel();
		pCenter.setLayout(new BorderLayout());
		JPanel pThuoc = new JPanel();
		pThuoc.setLayout(new BoxLayout(pThuoc, BoxLayout.X_AXIS));
		JLabel lblTenThuoc = new JLabel("Tên thuốc");
		txtTenThuoc = new JTextField(20);
		JLabel lblSoLuong = new JLabel("Số lượng");
		txtSoLuong = new JTextField(5);
		JLabel lblDonGia = new JLabel("Đơn giá");
		txtDonGia = new JTextField(10);
		pThuoc.add(lblTenThuoc);
		pThuoc.add(txtTenThuoc);
		pThuoc.add(lblSoLuong);
		pThuoc.add(txtSoLuong);
		pThuoc.add(lblDonGia);
		pThuoc.add(txtDonGia);
		pCenter.add(pThuoc,BorderLayout.NORTH);
		JPanel pButton = new JPanel();
		pButton.setLayout(new BoxLayout(pButton, BoxLayout.Y_AXIS));
		pButton.add(Box.createRigidArea(new Dimension(0, 80)));
		btnThem = new JButton("   Thêm  ");
		btnXoa = new JButton("   Xóa     ");
		btnQuayLai = new JButton("Quay lại ");
		pButton.add(btnThem);
		pButton.add(Box.createRigidArea(new Dimension(0, 50)));
		pButton.add(btnXoa);
		pButton.add(Box.createRigidArea(new Dimension(0, 50)));
		pButton.add(btnQuayLai);
		pCenter.add(pButton,BorderLayout.EAST);
		String[] header = {"Tên thuốc","Số lượng","Đơn giá","Thành tiền"};
		model = new DefaultTableModel(header,0);
		table = new JTable(model);
		JScrollPane scroll = new JScrollPane(table, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
		pCenter.add(scroll,BorderLayout.CENTER);
		pMain.add(pCenter,BorderLayout.CENTER);
		Border borderCenter = BorderFactory.createLineBorder(Color.BLUE);
		pCenter.setBorder(borderCenter);
		pButton.setBackground(Color.pink);
		pCenter.setBorder(borderCenter);
		JPanel pSouth = new JPanel();
		JLabel lblTongTien = new JLabel("Tổng thành tiền :");
		txtTongTien = new JTextField(15);
		txtTongTien.setEditable(false);
		pSouth.add(lblTongTien);
		pSouth.add(txtTongTien);
		pMain.add(pSouth,BorderLayout.SOUTH);
		Border borderSouth = BorderFactory.createLineBorder(Color.BLUE);
		pSouth.setBorder(borderSouth);
		pSouth.setBackground(Color.pink);
		//Container con = this.getContentPane();
		//con.add(pMain);
	}
}